[tool.poetry]
name = "watchmen-data-product"
version = "0.1.0"
description = ""
authors = ["luke0623 <luke0623@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
